### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by VincentEnRoueLibre** [Tructruc/SAE-ALT-S3-Dev-23-24-Occupation-salles-3A-Groupe-2#71]
Hello le groupe 2, je vous signale une petite faute d'orthographe dans votre readme, dans la partie [Présentation du projet](https://github.com/Tructruc/SAE-ALT-S3-Dev-23-24-Occupation-salles-3A-Groupe-2?tab=readme-ov-file#pr%C3%A9sentation-du-projet)

> Le client, M. Boulle, nous a donc ~missionn**er**~ missionn**é**

@Tructruc @enzofrnt pas besoin de me remercier 😹🤙

**Comment by enzofrnt** [comment]
Merci @VincentEnRoueLibre ! 
Nous avons corrigé ce probléme !

**Comment by VincentEnRoueLibre** [comment]
Félicitations [Enzo Fournet](https://github.com/enzofrnt)
